iap2/iap2/Pages/AdminDash.cshtml.cs
using iap2.Model;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace iap2.Pages
{
    public class AdminDashModel : PageModel
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<AppUser> _userManager;
        public List<IdentityRole> roles { get; set; }
        public List<AppUser> users { get; set;}
        public List<UserRolesViewModel> rolesViewModel { get; set; }
        public List<UserRolesViewModel> userRolesViewModel { get; set; }
        [BindProperty(SupportsGet = true)]
        public string Id { get; set; }
        [BindProperty]
        public string passwordString { get; set; }
        [BindProperty]
        public string roleName { get; set; }
        public AdminDashModel(RoleManager<IdentityRole> roleManager, UserManager<AppUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            roles = await _roleManager.Roles.ToListAsync();
            users = await _userManager.Users.ToListAsync();
            userRolesViewModel = new List<UserRolesViewModel>();
            foreach (AppUser user in users)
            {
                var thisViewModel = new UserRolesViewModel();
                thisViewModel.Id = user.Id;
                thisViewModel.Email = user.Email;
                thisViewModel.FirstName = user.FirstName;
                thisViewModel.LastName = user.LastName;
                thisViewModel.Roles = await GetUserRoles(user);
                userRolesViewModel.Add(thisViewModel);
            }
            return Page();
        }
        public async Task<IActionResult> OnGetDelete()
        {
            var role = await _roleManager.FindByIdAsync(Id);
            var user = await _userManager.FindByIdAsync(Id);
            if (role != null)
            {
                await _roleManager.DeleteAsync(role);
            }
            else if (user != null)
            {
                await _userManager.DeleteAsync(user);
            }
            return RedirectToPage("AdminDash");
        }
        public async Task<IActionResult> OnPostAsync()
        {
            if (roleName != null)
            {
                await _roleManager.CreateAsync(new IdentityRole(roleName.Trim()));
            }
            else
            {
                ModelState.AddModelError("", "No role specified");
            }
            return RedirectToPage("AdminDash");
        }
        public async Task<IActionResult> OnPostUpdateAsync()
        {
            var users = await _userManager.FindByIdAsync(Id);
            await _userManager.RemovePasswordAsync(users);
            await _userManager.AddPasswordAsync(users, passwordString);
            return RedirectToPage("AdminDash");
        }

        private async Task<List<string>> GetUserRoles(AppUser user)
        {
            return new List<string>(await _userManager.GetRolesAsync(user));
        }
    }
}

//var a = await _userManager.GetRolesAsync(user);

iap2/iap2/Pages/Cart.cshtml.cs
using iap2.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Linq;

namespace iap2.Pages
{
    [Authorize(Roles = "AdminManager, Visitor")]
    public class CartModel : PageModel
    {
        [BindProperty (SupportsGet = true)]
        public int Id { get; set; }
        public IEnumerable<CartItem> cartItemsList { get; set; }
        private readonly AppDataContext _db;
        private readonly UserManager<AppUser> _userManager;
        public double totalForProduct { get; set; }
        public double total { get; set; }

        public CartModel(AppDataContext db, UserManager<AppUser> userManager)
        {
            _db = db;
            _userManager = userManager;
        }
        public void OnGet()
        {
            string d = _userManager.GetUserId(User);
            cartItemsList = _db.ShoppingCartItems.Where(c => c.CartId == d).ToList();
            foreach (var item in cartItemsList)
            {
                item.Products = _db.Products.Find(item.ProductId);
                totalForProduct = item.Quantity * item.Products.Price;
                totalForProduct = Math.Round(totalForProduct, 2);
                total += totalForProduct;
            }
            total = Math.Round(total, 2);

        }
        public IActionResult OnGetDelete()
        {
            var it = _db.ShoppingCartItems.Find(Id);
            if (it.Quantity > 1)
            {
                it.Quantity--;
            }
            else
            {
                _db.Remove(_db.ShoppingCartItems.Find(Id));
            }
            _db.SaveChanges();
            return RedirectToPage("Cart");
        }
        public IActionResult OnGetAdd()
        {
            var it = _db.ShoppingCartItems.Find(Id);
            it.Quantity++;
            _db.SaveChanges();
            return RedirectToPage("Cart");
        }
        public IActionResult OnGetOrder()
        {
            string d = _userManager.GetUserId(User);
            cartItemsList = _db.ShoppingCartItems.Where(c => c.CartId == d).ToList();
            foreach (var item in cartItemsList)
            {
                _db.Remove(_db.ShoppingCartItems.Find(item.Id));
            }
            _db.SaveChanges();
            return RedirectToPage("Thank");
        }
    }
}

iap2/iap2/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace iap2.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

iap2/iap2/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace iap2.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

iap2/iap2/Pages/Manage.cshtml.cs
using iap2.Model;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace iap2.Pages
{
    public class ManageModel : PageModel
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<AppUser> _userManager;
        public ManageModel(RoleManager<IdentityRole> roleManager, UserManager<AppUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        [BindProperty(SupportsGet = true)]       
        public string Id { get; set; }
        [BindProperty (SupportsGet = true)]
        public bool Selected { get; set; }
        public AppUser Indicate { get; set; }
        public List<ManageUserRolesViewModel> model { get; set; }
        public async Task<IActionResult> OnGetAsync()
        {
            Indicate = await _userManager.FindByIdAsync(Id);
            model = new List<ManageUserRolesViewModel>();
            foreach (var role in _roleManager.Roles.ToList())
            {
                var userRolesViewModel = new ManageUserRolesViewModel
                {
                    RoleId = role.Id,
                    RoleName = role.Name
                };
                if (await _userManager.IsInRoleAsync(Indicate, role.Name))
                {
                    userRolesViewModel.Selected = true;
                }
                else
                {
                    userRolesViewModel.Selected = false;
                }
                model.Add(userRolesViewModel);
            }
            return Page();
        }
        public async Task<IActionResult> OnPostAsync()
        {
            var user = await _userManager.FindByIdAsync(Id);
            if (user == null)
            {
                return Page();
            }
            var roles = await _userManager.GetRolesAsync(user);
            if (roles == null)
            {
                return Page();
            }
            /*
            var result = await _userManager.RemoveFromRolesAsync(user, roles);
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot remove user existing roles");
                return Page();
            }
            var new_roles1 = model.Where(s => s.Selected == true);
            var new_roles2 = new_roles1.Select(y => y.RoleName);
            result = await _userManager.AddToRolesAsync(user, new_roles2);
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot add selected roles to user");
                return Page();
            }*/
            return RedirectToPage("AdminDash");
        }
    }
}

iap2/iap2/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace iap2.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

iap2/iap2/Pages/SingleProduct.cshtml.cs
using iap2.Model;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Linq;

namespace iap2.Pages
{
    public class SingleProductModel : PageModel
    {
        [BindProperty]
        public Product item { get; set; }
        [BindProperty (SupportsGet = true)]
        public int Id { get; set; }
        private readonly AppDataContext _db;
        private readonly UserManager<AppUser> _userManager;

        public SingleProductModel(AppDataContext db, UserManager<AppUser> userManager)
        {
            _db = db;
            _userManager = userManager;
        }
        public void OnGet()
        {
            item = _db.Products.Find(Id);
        }
        public IActionResult OnPost()
        {
            string cartOwner = _userManager.GetUserId(User);
            var itemExists = _db.ShoppingCartItems.SingleOrDefault(c => c.CartId == cartOwner && c.ProductId == Id);
            if (itemExists == null)
            {
                CartItem cartItem = new CartItem()
                {
                    ProductId = Id,
                    CartId = cartOwner,
                    Quantity = 1,
                    DateCreated = DateTime.Now
                };

                _db.ShoppingCartItems.Add(cartItem);
            }
            else
            {
                itemExists.Quantity++;
            }
            _db.SaveChanges();
            return RedirectToPage("Cart");
        }
    }
}

iap2/iap2/Pages/Thank.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace iap2.Pages
{
    public class ThankModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

iap2/iap2/Pages/addProduct.cshtml.cs
using iap2.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace iap2.Pages
{
    [Authorize (Roles = "AdminManager")]
    public class addProductModel : PageModel
    {
        [BindProperty]
        public Product item { get; set; }
        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }

        private readonly AppDataContext _db;

        public addProductModel(AppDataContext db)
        {
            _db = db;
        }
        public void OnGet()
        {
            item = _db.Products.Find(Id);
        }
        public IActionResult OnPost()
        {
            _db.Products.Add(item);
            _db.SaveChanges();
            return RedirectToPage("products");
        }
        public IActionResult OnPostUpdate()
        {
            _db.Products.Update(item);
            _db.SaveChanges();
            return RedirectToPage("products");
        }
    }
}

iap2/iap2/Pages/products.cshtml.cs
using iap2.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;

namespace iap2.Pages
{
    public class productsModel : PageModel
    {
        [BindProperty]
        public string searchString { get; set; }
        [BindProperty (SupportsGet = true)]
        public string category { get; set; }
        public IEnumerable<Product> itemsList { get; set; }
        public List<Product> products { get; set; }
        public IEnumerable<string> ProdCategories { get; set; }

        [BindProperty (SupportsGet = true)]
        public int Id { get; set; }
        public Product Recommen1 { get; set; }

        public Product Recommen2 { get; set; }

        private readonly AppDataContext _db;

        static Random rnd = new Random();
        public productsModel(AppDataContext db)
        {
            _db = db;
        }
        public void OnGet()
        {
            itemsList = _db.Products.ToList();
            products = _db.Products.ToList();
            int r = rnd.Next(products.Count);
            if (r == products.Count-1)
            {
                Recommen1 = products[r];
                Recommen2 = products[r-1];
            }
            else
            {
                Recommen1 = products[r];
                Recommen2 = products[r+1];
            }           
            ProdCategories = _db.Products.Select(p => p.Category).Distinct();
        }
        public void OnPost()
        {
            ProdCategories = _db.Products.Select(p => p.Category).Distinct();
            itemsList = _db.Products.Where(p => p.Description.Contains(searchString));
        }
        public void OnPostCategory()
        {
            ProdCategories = _db.Products.Select(p => p.Category).Distinct();
            string ctg = Request.Form["categSearch"];
            itemsList = _db.Products.Where(p => p.Category.Contains(ctg));
        }
        public IActionResult OnGetDelete()
        {
            _db.Remove(_db.Products.Find(Id));
            _db.SaveChanges();
            return RedirectToPage("products");
        }
    }
}

iap2/iap2/Pages/AdminDash.cshtml
@page
@model iap2.Pages.AdminDashModel
@{
}

<p id="roleH">Role management</p>

<form method="post">
    <div>
        <input class="searchBar" asp-for=@Model.roleName placeholder="New role.."/>
        <input class="searchButton" type="submit" value="ADD ROLE" />
    </div>
</form>

<table class="rolesTable">
    <tr>
        <th>Id</th>
        <th>Role name</th>
        <th>Delete</th>
    </tr>
    @foreach (var role in Model.roles)
    {
        <tr class="singleRole">
            <td>@role.Id</td>
            <td>@role.Name</td>
            <td><a class="passButton" asp-page="AdminDash" asp-route-id="@role.Id" asp-page-handler="Delete">Delete role</a></td>
        </tr>
    }
</table>

<p id="userH">User management</p>

<table class="usersBox">
    <tr>
        <th>Email</th>
        <th>Roles</th>
        <th>Update password</th>
        <th>Action</th>
        <th>Delete</th>
    </tr>
    @foreach (var user in Model.userRolesViewModel)
    {
        <tr class="singleUser">
            <td>@user.Email</td>
            <td>@string.Join(" , ", user.Roles.ToList())</td>            
            <td id="passTd">
                <form method="post" asp-page-handler="Update" asp-route-id="@user.Id">
                    <input class="passBox" asp-for="passwordString" placeholder="New password.."/>
                    <input id="passButt" type="submit" value="Update" />
                </form>
            </td>
            <td><a class="passButton" asp-page="Manage" asp-route-id="@user.Id">Manage</a></td>
            <td><a class="passButton" asp-page="AdminDash" asp-route-id="@user.Id" asp-page-handler="Delete">Delete</a></td>
        </tr>
    }
</table>

iap2/iap2/Pages/Cart.cshtml
@page
@model iap2.Pages.CartModel
@{
}
<p class="info">Your cart</p>
<table class="cartBox" id="cart">
    <tr>
        <th class="imageTable">Image</th>
        <th class="nameTable">Name</th>
        <th class="priceTable">Price (each)</th>
        <th class="qntTable">Quantity</th>
        <th class="editTable">Edit</th>
    </tr>
    <form method="post">
        @if (!Model.cartItemsList.Any())
        {
            <tr>
                <td colspan="6" id="emptyCart">Your cart is empty</td>
            </tr>
        }
        @foreach (var cartItem in Model.cartItemsList)
            {
                <tr class="cartItem">
                    <td class="imageTable"><img class="previewImg" src="./assets/@cartItem.Products.ProductImage" alt="@cartItem.Products.ProductImageAlt"></td>
                    <td class="nameTable">@cartItem.Products.Name</td>
                    <td class="priceTable" id="prodPrice">@cartItem.Products.Price $</td>
                    <td class="qntTable" id="prodQnt">@cartItem.Quantity</td>
                    <td class="editTable">
                        <a class="edits" asp-page="Cart" asp-route-id="@cartItem.Id" asp-page-handler="Add">+</a>

                        <a class="edits" asp-page="Cart" asp-route-id="@cartItem.Id" asp-page-handler="Delete">—</a>
                    </td>
                </tr>
            }
            <tr>
                <td colspan="3" class="total">Total</td>
                <td colspan="3" class="total">@Model.total $</td>
            </tr>
    </form>
</table>
@if (Model.cartItemsList.Any())
{
    <p class="info">CHECKOUT</p>
    <form method="post" class="checkF">
        <p class="naming">DELIVERY ADDRESS</p>
        <div>
            <input placeholder="House number.."/>
        </div>
        <div>
            <input placeholder="Street.."/>
        </div>
        <div>
            <input placeholder="Post code.."/>
        </div>
        <div>
            <input placeholder="City.."/>
        </div>
        <div>
            <input placeholder="Country.."/>
        </div>
        <p class="naming">BILLING ADDRESS</p>
        <div>
            <input placeholder="House number.."/>
        </div>
        <div>
            <input placeholder="Street.."/>
        </div>
        <div>
            <input placeholder="Post code.."/>
        </div>
        <div>
            <input placeholder="City.."/>
        </div>
        <div>
            <input placeholder="Country.."/>
        </div>
        <p class="naming">PAYMENT DETAILS</p>
        <div>
            <input placeholder="Card number.."/>
        </div>
        <div>
            <input placeholder="Cartholder name.."/>
        </div>
        <div>
            <input placeholder="Expiry date.."/>
        </div>
        <div>
            <input placeholder="CVC code.."/>
        </div>
        <p class="naming">AMOUNT TO PAY: @Model.total $</p>
        <a class="checkoutButton" asp-page-handler="Order">PAY</a>
    </form>
}

iap2/iap2/Pages/Index.cshtml
@page
@model IndexModel
@{
}

<div>
    <section id="vid">
        <video id="show_vid" playsinline autoplay muted></video>
    </section>
    <section id="pic_n_txt1">
        <section class="show">
            <img id="showcase1" src="../assets/showcase10.png" alt="Bottle">
        </section>
        <section id="text_home1">
            <p>DECIEM is a humble and happy umbrella of good beauty brands like NIOD, 
            Hylamide, and The Ordinary. We’ve been called every good and bad thing you 
            can think of like “The most thrilling thing to happen to skincare” and 
            “The hottest beauty company right now”.</p>
        </section>
    </section>
    <section id="pic_n_txt2">
        <section id="text_home2">
            <p>Everything we do is of exceptional quality. Today, quality is no longer
            defined by merely price points or distribution channels. Quality today 
            means being authentic, being different, being functional, being beautiful 
            and being sensibly priced, even to the wealthy. And we respect these principles. 
            We choose to serve the educated, the curious and the intelligent who 
            appreciate our dedication to this very genuine definition of quality.</p>
            <p>Over the past year, we’ve sold more than one product every second, 
            opened the doors to our 35th store, and welcomed our 1000th employee. With many
            products in development, a new 70,000 square-foot HQ to call home, and plans 
            for even further retail expansion, we are excited to do even bigger things in 2021.</p>
        </section>
        <section class="show">
            <img id="showcase2" src="../assets/showcase4.png" alt="Bottle">
        </section>
    </section>
</div>

iap2/iap2/Pages/Manage.cshtml
@page
@model iap2.Pages.ManageModel
@{
}
<form method="post">
    <div class="card">
        <div class="card-header">
            <h3>MANAGE USER ROLES</h3>
            <h5>@Model.Indicate.Email</h5>
        </div>
        <div class="card-body">
            @foreach (var role in @Model.model)
            {
                <div class="form-check m-1">
                    <input type="hidden" asp-for="@role.RoleId" />
                    <input type="hidden" asp-for="@role.RoleName" />
                    <input asp-for="@role.Selected" class="form-check-input" />
                    <label class="form-check-label" asp-for="@role.Selected">
                        @role.RoleName
                    </label>
                </div>
            }
            <div asp-validation-summary="All" class="text-danger"></div>
        </div>
        <div class="card-footer">
            <input id="buttonC" type="submit" value="UPDATE" class="btn btn-primary"
                   style="width:auto" />
            <a id="buttonD" asp-page="AdminDash" asp-route-id="Id"
               class="btn btn-primary" style="width:auto">Cancel</a>
        </div>
    </div>
</form>

iap2/iap2/Pages/SingleProduct.cshtml
@page
@model iap2.Pages.SingleProductModel
@{
}
<form method="post">
    <div class="imageHalf">
        <img class="previewImg" src="./assets/@Model.item.ProductImage" alt="@Model.item.ProductImageAlt">
        <img class="previewImg" src="./assets/@Model.item.ProductImagePage2" alt="@Model.item.ProductImagePage2Alt">
        <img class="previewImg" src="./assets/@Model.item.ProductImagePage3" alt="@Model.item.ProductImagePage3Alt">
    </div>
    <div class="descriptionHalf">
        <p class="brandName">The Ordinary</p>
        <p class="title">@Model.item.Name</p>
        <p id="size">@Model.item.Size</p>
        <p id="priceProduct">@Model.item.Price $</p>
        <p>@Model.item.Description</p>
        <p id="ingredients">Ingredients: @Model.item.Ingredients</p>
        <input class="buy" asp-route-id="@Model.item.Id" type="submit" value="ADD TO CART" />
    </div>
</form>

iap2/iap2/Pages/Thank.cshtml
@page
@model iap2.Pages.ThankModel
@{
}
<div id="conf">
    <h1>Thank you!</h1>
    <h5>We accepted your order</h5>
    <h5>You should receive an email confirmation soon</h5>
</div>

iap2/iap2/Pages/addProduct.cshtml
@page
@model iap2.Pages.addProductModel
@{
}

<p class="info">Fill in the form to add/edit a product</p>
<form method="post" class="createProd">
    <div>
        <label asp-for=@Model.item.Id>ID</label>
        <input asp-for=@Model.item.Id readonly placeholder="Assigned automatically"/>
    </div>
    <div>
        <label asp-for=@Model.item.Name>NAME</label>
        <input asp-for=@Model.item.Name  placeholder="Product name.."/>
    </div>
    <div>
        <label asp-for=@Model.item.Description>DESCRIPTION</label>
        <textarea class="prodBig" asp-for=@Model.item.Description placeholder="Product description.."></textarea>
    </div>
    <div>
        <label asp-for=@Model.item.Size>SIZE</label>
        <input asp-for=@Model.item.Size placeholder="Product size.."/>
    </div>
    <div>
        <label asp-for=@Model.item.Ingredients>INGREDIENTS</label>
        <textarea class="prodBig" asp-for=@Model.item.Ingredients placeholder="Product ingredients.."></textarea></>
    </div>
    <div>
        <label asp-for=@Model.item.Price>PRICE</label>
        <input asp-for=@Model.item.Price placeholder="Product price $.."/>
    </div>
    <div>
        <label asp-for=@Model.item.Category>CATEGORY</label>
        <input asp-for=@Model.item.Category placeholder="Product category.."/>
    </div>
    <div>
        <label asp-for=@Model.item.ProductImage>MAIN IMAGE</label>
        <input asp-for=@Model.item.ProductImage placeholder="Product image.."/>
    </div>
    <div>
        <label asp-for=@Model.item.ProductImageAlt>ALT FOR MAIN IMAGE</label>
        <input asp-for=@Model.item.ProductImageAlt placeholder="Alternative text for image.."/>
    </div>
    <div>
        <label asp-for=@Model.item.ProductImagePage2>IMAGE 2</label>
        <input asp-for=@Model.item.ProductImagePage2 placeholder="Product image 2.."/>
    </div>
    <div>
        <label asp-for=@Model.item.ProductImagePage2Alt>ALT FOR IMAGE 2</label>
        <input asp-for=@Model.item.ProductImagePage2Alt placeholder="Alternative text for image 2.."/>
    </div>
    <div>
        <label asp-for=@Model.item.ProductImagePage3>IMAGE 3</label>
        <input asp-for=@Model.item.ProductImagePage3 placeholder="Product image 3.."/>
    </div>
    <div>
        <label asp-for=@Model.item.ProductImagePage3Alt>ALT FOR IMAGE 3</label>
        <input asp-for=@Model.item.ProductImagePage3Alt placeholder="Alternative text for image 3.."/>
    </div>
    <div id="buttonsP">
        <input class="buttonAdd" type="submit" value="ADD PRODUCT" />
        <input class="buttonAdd" type="submit" asp-page-handler="Update" value="SAVE CHANGES" />
    </div>
</form>

iap2/iap2/Pages/products.cshtml
@page
@using Microsoft.AspNetCore.Identity
@using iap2.Model;
@inject SignInManager<AppUser> SignInManager;
@model iap2.Pages.productsModel
@{
}
@{

}

@{
    if (@Model.Recommen1 != null && @Model.Recommen2 != null)
    {
        <div class="recomBox">
            <p id="tit">Recommedations for you</p>
            <div class="singleRecom1">        
                <img src="./assets/@Model.Recommen1.ProductImage" alt="@Model.Recommen1.ProductImageAlt">
                <a class="txtB" asp-page="SingleProduct" asp-route-id="@Model.Recommen1.Id">@Model.Recommen1.Name</a>
                <p class="txtR">@Model.Recommen2.Price $</p>
            </div>
            <div class="singleRecom2">        
                <img src="./assets/@Model.Recommen2.ProductImage" alt="@Model.Recommen2.ProductImageAlt">
                <a class="txtB" asp-page="SingleProduct" asp-route-id="@Model.Recommen2.Id">@Model.Recommen2.Name</a>
                <p class="txtR">@Model.Recommen2.Price $</p>
            </div>    
        </div>
    }
}


<form method="post" class="search"> 
    <input class="searchBar" asp-for="searchString" placeholder="Search.." />
    <input class="searchButton" type="submit" value="SUBMIT" /> 
</form>


<form method="post" class="categ">
    <label id="dropdLabel" asp-for="category">CATEGORIES:</label>    
    <select name="categSearch" id="dropdown">
        @foreach (string category in Model.ProdCategories)
        {
            <option asp-for="category" value="@category">@category</option>
        }
    </select>
    <input class="sButton" asp-page-handler="Category" type="submit" value="Search" />
</form>

<div class="itemsBox">
    @foreach (var product in Model.itemsList)
    {
        <div class="singleItem">           
            <img class="previewImg" src="./assets/@product.ProductImage" alt="@product.ProductImageAlt">
            <p class="brand">The Ordinary.</p>
            <a class="itemName" asp-page="SingleProduct" asp-route-id="@product.Id">@product.Name</a>
            <p class="price">@product.Price $</p>
            <p class="size">@product.Size</p>
            @{
                if (SignInManager.IsSignedIn(User) && User.IsInRole("AdminManager"))
                {
                    <a class="adminButton" asp-page="addProduct" asp-route-id="@product.Id">EDIT</a>
                    <a class="adminButton" asp-page="products" asp-route-id="@product.Id" asp-page-handler="Delete">DELETE</a>
                }
            }  
        </div>
    }
</div>